// <auto-generated />
using System;
using DotnetEFRazorCompSSR.App.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DotnetEFRazorCompSSR.Server.Migrations
{
    [DbContext(typeof(WebsitesContext))]
    partial class WebsitesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DotnetEFRazorCompSSR.App.Models.Website", b =>
                {
                    b.Property<int>("WebsiteId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Url");

                    b.HasKey("WebsiteId");

                    b.ToTable("Websites");
                });

            modelBuilder.Entity("DotnetEFRazorCompSSR.App.Models.WebsiteDetail", b =>
                {
                    b.Property<int>("WebsiteDetailId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("TotalVisits");

                    b.Property<DateTime>("VisitDate");

                    b.Property<int>("WebsiteId");

                    b.HasKey("WebsiteDetailId");

                    b.HasIndex("WebsiteId");

                    b.ToTable("WebsiteDetails");
                });

            modelBuilder.Entity("DotnetEFRazorCompSSR.App.Models.WebsiteDetail", b =>
                {
                    b.HasOne("DotnetEFRazorCompSSR.App.Models.Website", "Website")
                        .WithMany("WebsiteDetails")
                        .HasForeignKey("WebsiteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
